/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controleacesso.apresentacao;

import controleacesso.dominio.Sistema;
import controleacesso.negocio.SistemaController;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * Classe que representa a janela de buscar um sistema por sigla.
 * Nela, o usuário pode fornecer uma sigla e obter o sistema correspondente.
 * @author leosilva
 */
public class ListarSistemaPorSigla extends javax.swing.JInternalFrame {

    // esta tela chama os método do controlador de sistemas. Assim, o controlador é instanciado nesta linha.
    SistemaController sistemaController = new SistemaController();

    
    /**
     * Creates new form ListarSistemaPorSigla
     */
    public ListarSistemaPorSigla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Sigla:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(35, 35, 35)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .add(jButton1)
                .add(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton1)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que representa a ação do botão de buscar um sistema pela sigla.
     * É chamado o método do controlador responsável pela operação, passando como parâmetro a sigla obtida do campo da tela.
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
             /*
             * chama o método listarSistemasPorSigla() do controlador, passando como parâmetro a sigla do sistema digitado em tela. 
             * Esse método passa a chamada para o DAO, que, por fim, realiza a consulta no banco de dados.
             */
            Sistema sistema = sistemaController.listarSistemasPorSigla(jTextField1.getText().trim());
            JOptionPane.showMessageDialog(null, "Sigla:" + sistema.getSigla() + "e Nome: " + sistema.getNome(), "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
         } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao listaR o sistema!", "Erro!", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
