/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controleacesso.apresentacao;

import controleacesso.relatorios.RelatorioUsuarios;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 * Classe que representa a janela principal do sistema.
 * A partir de um menu, o usuário pode acessar as outras telas do sistema.
 * @author leosilva
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuCadastrosBasicos = new javax.swing.JMenu();
        jMenuSistema = new javax.swing.JMenu();
        jMenuItemNovoSistema = new javax.swing.JMenuItem();
        jMenuItemListarSistema = new javax.swing.JMenuItem();
        jMenuItemListarPorSigla = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelatorioUsuarios = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        org.jdesktop.layout.GroupLayout jInternalFrame1Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuArquivo.setText("Arquivo");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuBar1.add(jMenuArquivo);

        jMenuCadastrosBasicos.setText("Cadastros Básicos");

        jMenuSistema.setText("Sistema");

        jMenuItemNovoSistema.setText("Novo");
        jMenuItemNovoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoSistemaActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemNovoSistema);

        jMenuItemListarSistema.setText("Listar");
        jMenuItemListarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarSistemaActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemListarSistema);

        jMenuItemListarPorSigla.setText("Listar Por Sigla");
        jMenuItemListarPorSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarPorSiglaActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemListarPorSigla);

        jMenuCadastrosBasicos.add(jMenuSistema);

        jMenuBar1.add(jMenuCadastrosBasicos);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemRelatorioUsuarios.setText("Lista de Usuários");
        jMenuItemRelatorioUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioUsuariosActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioUsuarios);

        jMenuBar1.add(jMenuRelatorios);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 735, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que instancia a janela de cadastro de um novo sistema.
     * @param evt 
     */
    private void jMenuItemNovoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoSistemaActionPerformed
        CadastroSistema cadastroSistema = new CadastroSistema();
        this.add(cadastroSistema);
        cadastroSistema.setVisible(true);
    }//GEN-LAST:event_jMenuItemNovoSistemaActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * Método que instancia a janela da listagem de sistemas.
     * @param evt 
     */
    private void jMenuItemListarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarSistemaActionPerformed
        ListarSistema listarSistema = new ListarSistema();
        this.add(listarSistema);
        listarSistema.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarSistemaActionPerformed

    /**
     * Método que instancia a janela da busca de um sistema pela sigla.
     * @param evt 
     */
    private void jMenuItemListarPorSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarPorSiglaActionPerformed
        ListarSistemaPorSigla listarSistema = new ListarSistemaPorSigla();
        this.add(listarSistema);
        listarSistema.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarPorSiglaActionPerformed

    private void jMenuItemRelatorioUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioUsuariosActionPerformed
        try {
            RelatorioUsuarios.gerarRelatorio();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao gerar o relatório. Tente novamente mais tarde.", "Erro!", JOptionPane.ERROR_MESSAGE);
        } catch (JRException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao gerar o relatório. Tente novamente mais tarde.", "Erro!", JOptionPane.ERROR_MESSAGE);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao gerar o relatório. Tente novamente mais tarde.", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemRelatorioUsuariosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrosBasicos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemListarPorSigla;
    private javax.swing.JMenuItem jMenuItemListarSistema;
    private javax.swing.JMenuItem jMenuItemNovoSistema;
    private javax.swing.JMenuItem jMenuItemRelatorioUsuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSistema;
    // End of variables declaration//GEN-END:variables
}
